### ISSUE TITLE
Set default language for all pages

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/jekyll-open-sdg-plugins#17]
Right now, a default language is being set by adding something like this to the `_config.yml`:

```
defaults:
  -
    scope:
      path: ""
    values:
      language: "es"
```

This works fine, but it's a little fragile because of all the indents, and looks confusing. Can we add a plugin here that will simply take the first item in `languages` and ensure all pages have this default?
